In [1]:
from numpy import array

In [2]:
T = array([[[1,2,3],[4,5,6],[7,8,9]],
          [[11,12,13],[14,15,16],[17,18,19]],
          [[21,22,23],[24,25,26],[27,28,29]]])

In [3]:
print(T.shape)

(3, 3, 3)


In [4]:
print(T)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


In [5]:
A = T

In [6]:
B = A

In [7]:
C = A+B

In [8]:
print(C)

[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[22 24 26]
  [28 30 32]
  [34 36 38]]

 [[42 44 46]
  [48 50 52]
  [54 56 58]]]


In [9]:
C = A-B

In [10]:
print(C)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [11]:
C = A*B

In [12]:
print(C)

[[[  1   4   9]
  [ 16  25  36]
  [ 49  64  81]]

 [[121 144 169]
  [196 225 256]
  [289 324 361]]

 [[441 484 529]
  [576 625 676]
  [729 784 841]]]


In [13]:
C = A/B

In [14]:
print(C)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [15]:
from numpy import tensordot

In [31]:
A = array([1,2])

In [32]:
B = array([1,2])

In [33]:
C = tensordot(A,B,axes=0)

In [34]:
print(C)

[[1 2]
 [2 4]]


In [39]:
A = array([[1,2],[3,4]])

In [40]:
B = array([[1,2],[3,4]])

In [47]:
C = tensordot(A,B,axes=0)

In [48]:
print(C)

[[[[ 1  2]
   [ 3  4]]

  [[ 2  4]
   [ 6  8]]]


 [[[ 3  6]
   [ 9 12]]

  [[ 4  8]
   [12 16]]]]
