In [10]:
#1 D array

In [2]:
from numpy import array

In [3]:
a = array([1,2,3])

In [4]:
print(a)

[1 2 3]


In [5]:
b = 2

In [6]:
print(b)

2


In [7]:
c = a+b

In [8]:
c

array([3, 4, 5])

In [11]:
# 2D array

In [12]:
A = array([[1,2,3],[1,2,3]])

In [13]:
print(A)

[[1 2 3]
 [1 2 3]]


In [14]:
b = 2

In [15]:
print(b)

2


In [16]:
C = A+b

In [17]:
print(C)

[[3 4 5]
 [3 4 5]]


In [18]:
# 1D and 2D arrays

In [19]:
A = array([[1,2,3],[1,2,3]])

In [20]:
print(A)

[[1 2 3]
 [1 2 3]]


In [21]:
b = array([1,2,3])

In [22]:
print(b)

[1 2 3]


In [23]:
C = A+b

In [24]:
print(C)

[[2 4 6]
 [2 4 6]]


In [38]:
b1 = array([[1]])

In [37]:
print(A+b1)

[[2 3 4]
 [2 3 4]]
