In [1]:
from numpy import array
from numpy import tril
from numpy import triu

In [2]:
M = array([[1,2,3],[1,2,3],[1,2,3]])

In [3]:
print(M)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [4]:
lower = tril(M)

In [5]:
print(lower)

[[1 0 0]
 [1 2 0]
 [1 2 3]]


In [6]:
upper = triu(M)

In [7]:
print(upper)

[[1 2 3]
 [0 2 3]
 [0 0 3]]


In [8]:
from numpy import diag

In [9]:
d = diag(M)

In [10]:
print(d)

[1 2 3]


In [11]:
D = diag(d)

In [12]:
print(D)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [13]:
from numpy import identity

In [14]:
I = identity(3)

In [15]:
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
from numpy.linalg import inv

In [17]:
Q = array([[1,0],[0,-1]])

In [18]:
print(Q)

[[ 1  0]
 [ 0 -1]]


In [19]:
V = inv(Q)

In [20]:
print(Q.T)

[[ 1  0]
 [ 0 -1]]


In [21]:
print(V)

[[ 1.  0.]
 [-0. -1.]]


In [22]:
I = Q.dot(Q.T)

In [23]:
print(I)

[[1 0]
 [0 1]]
