In [1]:
from numpy import array
from scipy.linalg import lu

In [2]:
A = array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
P,L,U = lu(A)

In [5]:
print(P)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [6]:
print(L)

[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]


In [7]:
print(U)

[[7.         8.         9.        ]
 [0.         0.85714286 1.71428571]
 [0.         0.         0.        ]]


In [8]:
B = P.dot(L).dot(U)

In [9]:
print(B)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [10]:
from numpy.linalg import qr

In [11]:
A = array([[1,2],[3,4],[5,6]])

In [12]:
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [13]:
Q, R = qr(A,'complete')

In [14]:
print(Q)

[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]


In [15]:
print(R)

[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]


In [16]:
B = Q.dot(R)

In [17]:
print(B)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [18]:
from numpy.linalg import cholesky

In [19]:
A = array([[2,1,1],[1,2,1],[1,1,2]])

In [20]:
print(A)

[[2 1 1]
 [1 2 1]
 [1 1 2]]


In [21]:
L = cholesky(A)

In [22]:
print(L)

[[1.41421356 0.         0.        ]
 [0.70710678 1.22474487 0.        ]
 [0.70710678 0.40824829 1.15470054]]


In [23]:
B = L.dot(L.T)

In [24]:
print(B)

[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]
