In [1]:
from numpy import array

In [2]:
l = [1.0,2.0,3.0]

In [3]:
a = array(l)

In [4]:
print(a)

[1. 2. 3.]


In [5]:
print(a.shape)

(3,)


In [6]:
print(a.dtype)

float64


In [7]:
from numpy import empty

In [8]:
a = empty([3,3])
print(a)

[[2.42660619e-316 6.94952622e-310 6.94952627e-310]
 [6.94951634e-310 6.94951634e-310 6.94951634e-310]
 [6.94951636e-310 6.94952631e-310 3.95252517e-322]]


In [9]:
from numpy import zeros
a = zeros([3,5])

In [10]:
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
from numpy import ones

In [14]:
a = ones([5])

In [15]:
print(a)

[1. 1. 1. 1. 1.]


In [16]:
# V stack

In [17]:
from numpy import array
from numpy import vstack

In [18]:
a1 = array([1,2,3])
print(a1)

[1 2 3]


In [19]:
a2 = array([4,5,6])
print(a2)

[4 5 6]


In [20]:
a3 = vstack((a1,a2))

In [21]:
print(a3)

[[1 2 3]
 [4 5 6]]


In [22]:
print(a3.shape)

(2, 3)


In [23]:
#Hstack

In [24]:
from numpy import hstack

In [25]:
a1 = array([1,2,3])
print(a1)

[1 2 3]


In [26]:
a2 = array([4,5,6])
print(a2)

[4 5 6]


In [27]:
a3 = hstack((a1,a2))

In [28]:
print(a3)

[1 2 3 4 5 6]


In [29]:
print(a3.shape)

(6,)
