In [1]:
from scipy.linalg import svd

In [2]:
from numpy import array

In [3]:
A = array([[1,2],[3,4],[5,6]])

In [4]:
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [5]:
U,s,V = svd(A)

In [6]:
print(U)

[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]


In [7]:
print(s)

[9.52551809 0.51430058]


In [8]:
print(V)

[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [9]:
# reconstruction

In [10]:
from numpy import diag
from numpy import zeros
from scipy.linalg import svd
from numpy import array

In [11]:
A = array([[1,2],[3,4],[5,6]])

In [12]:
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [13]:
U,s,V = svd(A)

In [14]:
Sigma = zeros((A.shape[0],A.shape[1]))

In [15]:
Sigma[:A.shape[1],:A.shape[1]] = diag(s)

In [16]:
B = U.dot(Sigma.dot(V))

In [17]:
print(B)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [18]:
A = array([[1,2,3],[4,5,6],[7,8,9]])

In [19]:
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
U,s,V = svd(A)

In [21]:
Sigma = diag(s)

In [22]:
B = U.dot(Sigma.dot(V))

In [23]:
print(B)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [24]:
# pseudoinverse

In [25]:
from numpy import array

In [26]:
from numpy.linalg import pinv

In [27]:
A = array([[0.1,0.2],[0.3,0.4],[0.5,0.6],[0.7,0.8]])

In [28]:
print(A)

[[0.1 0.2]
 [0.3 0.4]
 [0.5 0.6]
 [0.7 0.8]]


In [29]:
B = pinv(A)

In [30]:
print(B)

[[-1.00000000e+01 -5.00000000e+00  1.42385628e-14  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]


In [31]:
U,s,V = svd(A)
d = 1.0/s
D = zeros(A.shape)

In [33]:
D[:A.shape[1],:A.shape[1]] = diag(d)

In [34]:
B = V.T.dot(D.T).dot(U.T)

In [35]:
print(B)

[[-1.00000000e+01 -5.00000000e+00  1.42578328e-14  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]


In [36]:
# Dimensionality reduction

In [37]:
A = array([
    [1,2,3,4,5,6,7,8,9,10],
    [11,12,13,14,15,16,17,18,19,20],
    [21,22,23,24,25,26,27,28,29,30]
])

In [38]:
print(A)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


In [39]:
U,s,V = svd(A)

In [40]:
Sigma = zeros((A.shape[0],A.shape[1]))

In [41]:
Sigma[:A.shape[0], :A.shape[0]] = diag(s)

In [42]:
n_elements = 2

In [43]:
Sigma = Sigma[:,:n_elements]

In [44]:
V = V[:n_elements,:]

In [45]:
B = U.dot(Sigma.dot(V))

In [46]:
print(B)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]]


In [47]:
T = U.dot(Sigma)

In [48]:
print(T)

[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]


In [49]:
T = A.dot(V.T)

In [50]:
print(T)

[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]


In [51]:
# sklearn

In [52]:
from sklearn.decomposition import TruncatedSVD

In [53]:
svd = TruncatedSVD(n_components=2)

In [54]:
svd.fit(A)

TruncatedSVD(algorithm='randomized', n_components=2, n_iter=5,
             random_state=None, tol=0.0)

In [55]:
result = svd.transform(A)

In [56]:
print(result)

[[18.52157747  6.47697214]
 [49.81310011  1.91182038]
 [81.10462276 -2.65333138]]
