In [1]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig

In [2]:
A = array([
    [1,2],
    [3,4],
    [5,6]
])

In [3]:
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [4]:
M = mean(A.T,axis=1)

In [5]:
C = A-M

In [6]:
V = cov(C.T)

In [7]:
values,vectors = eig(V)

In [8]:
print(vectors)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [9]:
print(values)

[8. 0.]


In [10]:
P = vectors.T.dot(C.T)

In [11]:
print(P.T)

[[-2.82842712  0.        ]
 [ 0.          0.        ]
 [ 2.82842712  0.        ]]


In [12]:
# sklearn

In [13]:
from sklearn.decomposition import PCA

In [14]:
A = array([
    [1,2],
    [3,4],
    [5,6]
])

In [15]:
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [16]:
pca = PCA(2)

In [17]:
pca.fit(A)

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [18]:
print(pca.components_)

[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]


In [19]:
print(pca.explained_variance_)

[8. 0.]


In [20]:
B = pca.transform(A)

In [21]:
print(B)

[[-2.82842712e+00 -2.22044605e-16]
 [ 0.00000000e+00  0.00000000e+00]
 [ 2.82842712e+00  2.22044605e-16]]
