In [1]:
from numpy import array

In [2]:
v = array([1,2,3])

In [3]:
print(v)

[1 2 3]


In [4]:
a = array([1,2,3])
print(a)

[1 2 3]


In [5]:
b = array([1,2,3])
print(b)

[1 2 3]


In [6]:
c = a+b

In [7]:
print(c)

[2 4 6]


In [8]:
a = array([1,2,3])
print(a)

[1 2 3]


In [9]:
b = array([0.5,0.5,0.5])
print(b)

[0.5 0.5 0.5]


In [10]:
c = a-b
print(c)

[0.5 1.5 2.5]


In [11]:
aa = array([1,2,3])
b = array([1,2,3])
print(a*b)

[1 4 9]


In [12]:
print(a/b)

[1. 1. 1.]


In [13]:
c = a.dot(b)

In [14]:
print(c)

14


In [15]:
s = 0.5

In [16]:
print(s*a)

[0.5 1.  1.5]
