In [1]:
from numpy import array
from numpy.linalg import eig

In [2]:
A = array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
values, vectors = eig(A)

In [5]:
print(values)

[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]


In [6]:
print(vectors)

[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [7]:
B = A.dot(vectors[:,0])

In [8]:
print(B)

[ -3.73863537  -8.46653421 -13.19443305]


In [9]:
C = vectors[:,0]*values[0]

In [10]:
print(C)

[ -3.73863537  -8.46653421 -13.19443305]


In [11]:
# Reconstruction

In [12]:
from numpy.linalg import inv
from numpy.linalg import eig
from numpy import diag

In [13]:
Q = vectors

In [14]:
R = inv(Q)

In [15]:
L = diag(values)

In [16]:
B = Q.dot(L).dot(R)

In [17]:
print(B)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
