In [1]:
from numpy import array
from numpy import mean

In [2]:
v = array([1,2,3,4,5,6])

In [3]:
print(v)

[1 2 3 4 5 6]


In [4]:
result = mean(v)

In [5]:
print(result)

3.5


In [6]:
M = array([
    [1,2,3,4,5,6],
    [1,2,3,4,5,6]
])

In [7]:
print(M)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]


In [8]:
col_mean = mean(M,axis = 0)

In [9]:
print(col_mean)

[1. 2. 3. 4. 5. 6.]


In [11]:
row_mean = mean(M,axis = 1)

In [12]:
print(row_mean)

[3.5 3.5]


In [13]:
from numpy import var

In [14]:
v = array([1,2,3,4,5,6])

In [15]:
print(v)

[1 2 3 4 5 6]


In [16]:
result = var(v,ddof=1)

In [17]:
print(result)

3.5


In [18]:
M = array([
    [1,2,3,4,5,6],
    [1,2,3,4,5,6]
])

In [19]:
print(M)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]


In [20]:
col_var = var(M, ddof=1, axis=0)

In [21]:
print(col_var)

[0. 0. 0. 0. 0. 0.]


In [22]:
row_var = var(M,ddof=1,axis=1)

In [24]:
print(row_var)

[3.5 3.5]


In [25]:
from  numpy import std

In [26]:
M = array([
    [1,2,3,4,5,6],
    [1,2,3,4,5,6]
])

In [27]:
print(M)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]


In [28]:
col_std = std(M,ddof=1,axis=0)

In [29]:
print(col_std)

[0. 0. 0. 0. 0. 0.]


In [30]:
row_std = std(M,ddof=1,axis=1)

In [31]:
print(row_std)

[1.87082869 1.87082869]


In [32]:
# covariance

In [33]:
from numpy import cov

In [34]:
x = array([1,2,3,4,5,6,7,8,9])

In [35]:
print(x)

[1 2 3 4 5 6 7 8 9]


In [36]:
y = array([9,8,7,6,5,4,3,2,1])

In [37]:
print(y)

[9 8 7 6 5 4 3 2 1]


In [38]:
Sigma = cov(x,y)[0,1]

In [39]:
print(Sigma)

-7.5


In [40]:
from numpy import corrcoef

In [41]:
corr = corrcoef(x,y)[0,1]

In [42]:
print(corr)

-1.0


In [43]:
X = array([
    [1,5,8],
    [3,5,11],
    [2,4,9],
    [3,6,10],
    [1,5,10]
])

In [44]:
print(X)

[[ 1  5  8]
 [ 3  5 11]
 [ 2  4  9]
 [ 3  6 10]
 [ 1  5 10]]


In [45]:
Sigma = cov(X.T)

In [46]:
print(Sigma)

[[1.   0.25 0.75]
 [0.25 0.5  0.25]
 [0.75 0.25 1.3 ]]
