In [1]:
from numpy import array

In [2]:
A = array([[1,2,3],[4,5,6]])

In [3]:
print(A)

[[1 2 3]
 [4 5 6]]


In [4]:
B = array([[1,2,3],[4,5,6]])

In [5]:
print(B)

[[1 2 3]
 [4 5 6]]


In [6]:
C = A+B

In [7]:
print(C)

[[ 2  4  6]
 [ 8 10 12]]


In [8]:
C = A-B

In [9]:
print(C)

[[0 0 0]
 [0 0 0]]


In [10]:
C=A*B

In [11]:
print(C)

[[ 1  4  9]
 [16 25 36]]


In [12]:
print(A/B)

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
A = array([[1,2],[3,4],[5,6]])

In [14]:
B = array([[1,2],[3,4]])

In [15]:
C = A.dot(B)

In [16]:
print(C)

[[ 7 10]
 [15 22]
 [23 34]]


In [17]:
D = A@B

In [18]:
print(D)

[[ 7 10]
 [15 22]
 [23 34]]


In [19]:
B = array([0.5,0.5])

In [20]:
C = A.dot(B)

In [21]:
print(C)

[1.5 3.5 5.5]


In [22]:
b = 0.5

In [23]:
print(A*b)

[[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]
