In [1]:
from numpy import array

In [2]:
A = array([[1,2],[3,4],[5,6]])

In [3]:
X = A.T

In [4]:
print(X)

[[1 3 5]
 [2 4 6]]


In [5]:
from numpy.linalg import inv

In [6]:
A = array([[1,2],[3,4]])

In [7]:
B = inv(A)

In [8]:
print(B)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [9]:
I = A.dot(B)

In [10]:
print(I)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [11]:
from numpy import trace

In [14]:
A = array([[1,2,3],[4,5,6],[7,8,9]])

In [15]:
B = trace(A)

In [16]:
print(B)

15


In [17]:
from numpy.linalg import det

In [18]:
A = array([[1,2,3],[4,5,6],[7,8,9]])

In [19]:
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
B = det(A)

In [21]:
print(B)

0.0


In [22]:
from numpy.linalg import matrix_rank

In [23]:
v1 = array([1,2,3])

In [24]:
print(v1)

[1 2 3]


In [25]:
vr1 = matrix_rank(v1)

In [26]:
print(vr1)

1


In [27]:
v2 = array([0,0,0,0,0])

In [28]:
vr2 = matrix_rank(v2)

In [29]:
print(vr2)

0


In [30]:
# matrix rank

In [31]:
M0 = array([[0,0],
           [0,0]])

In [32]:
mr0 = matrix_rank(M0)

In [33]:
M1 = array([[1,2],[1,2]])

In [34]:
mr1 = matrix_rank(M1)

In [35]:
print(mr0)

0


In [36]:
print(mr1)

1


In [37]:
M2 = array([[1,2],[3,4]])

In [38]:
print(M2)

[[1 2]
 [3 4]]


In [39]:
mr2 = matrix_rank(M2)

In [40]:
print(mr2)

2
